language: python
python:
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "sudo apt-get install -y libacl1-dev"
  - "pip install --install-option=--no-cython-compile https://github.com/cython/cython/archive/c9eda12b4806fba3931f7b791be7a672c92d9ca0.zip"
  - "pip install -e ."
# command to run tests
script: python -m attic.testsuite.run -vb
