language: python
python:
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "sudo apt-get install -y libacl1-dev"
  - "pip install --install-option=--no-cython-compile https://github.com/cython/cython/archive/443369fc35ac35525eb4241548cad79d0c94f8dc.zip"
  - "pip install -e ."
# command to run tests
script: python -m attic.testsuite.run -vb
