language: python
python:
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "sudo apt-get install -y libacl1-dev"
  - "pip install --install-option=--no-cython-compile https://github.com/cython/cython/archive/5c9cbb6184d84204cc583e1fa52ec2b9bb3ab60a.zip"
  - "pip install -e ."
# command to run tests
script: python -m attic.testsuite.run -vb
